### ISSUE TITLE
Write a feature spec to test the API key usage with clearance.

### ISSUE THREAD

**Issue by drapergeek** [drapergeek/luckycharms#14]
We cannot test the API key stuff with clearance through a controller spec since it does not execute the full stack so we should have a single test that tests that functionality and then the controller specs should simply stub that out.

**Comment by brentm5** [comment]
Wait why are we testing the API with clearance. Shouldn't we be creating our own authentication via api key for the API and using clearance for the management front end ?

**Comment by drapergeek** [comment]
Clearance should always be the one who handles whether or not a use is authenticated. Otherwise, we'll duplicate logic. We obviously won't use the clearance views from the API.

**Comment by brentm5** [comment]
Clearance is just username password not key based authenticaion is it?

**Comment by drapergeek** [comment]
That is correct but once you've done your own check you can then use the same helpers for checking that. So it goes through the same system.

**Comment by brentm5** [comment]
Seems like a little bit overkill as each request is going to need to be authenticated.  If we were storing cookies and keeping track of user sessions for units I would say yes this makes sense.  However the api should be stateless and each request should provide an api key

**Comment by drapergeek** [comment]
It definitely is going to be authenticated each time but it also doesn't make sense to have one version of signed in that uses clearance and one version that does not. Yes, technically it still is stateless but 'signed_in?' or 'authorized?" should be the same methods no matter where you are in the app.

**Comment by brentm5** [comment]
I don't agree with that, I think it would be a good idea to have them similar but since they are vastly different I don't they should be put together.  In reality they are two separate parts of the site.  We don't technically even need to have signed_in?  all we need is authroized? really.

**Comment by drapergeek** [comment]
Why would tracking users be handled in two different ways? Lets say that in a year you want to add a new feature that allows you to remove all users who haven't authenticated in the past 6 months because they obviously aren't using the system. If you use a different method of signed_in, then you have to implement that call in two different ways.

**Comment by brentm5** [comment]
In reality they are two separate things.  The API level authentication is very simple and does need to keep track of sessions information.  The only benefit I see is if you want to add stuff later (key word is if) you can add it in one place.  Where as right now you can not use controller tests.  It adds extra things you don't need.  And its a completely different log in method (ie via an API key) .  Just doesn't seem like the best way to go about it.  It would be nice if these things could share common aspects but couldn't that be achieved via a helper class that encapsulates common functionality therefore keeping the authentication separate as well?

**Comment by drapergeek** [comment]
This is complete.
