### ISSUE TITLE
Registering devices based on mac addresses 

### ISSUE THREAD

**Issue by brentm5** [drapergeek/luckycharms#2]
The idea being that we will use the units mac address as the UID of the unit.  When the unit connects to the server for the first time it will have a model record generated to associated the unit with a name.

**Comment by drapergeek** [comment]
So at that point would you even need an API key or would we turn on an off registratoin and basically use the Mac address as the API key?

**Comment by brentm5** [comment]
That would be a way to tell which device it is, I dont know if it is the best thing to use as the api key as that information is accessible on the network.  I would say its more of like a unique username?  From a security standpoint it doesnt seem all that good.  But then again at this moment its only just receiving info so i don't know if that matters very much

**Comment by drapergeek** [comment]
So here is what I'm thinking:
Call from unit to server: 'Send over name and mac address'
Response from server: 'send back unique API key that is generated for the device.'
The unit should store this API key. On all subsequent requests, we actually do not look at that the mac adress at all but the API key as that will be a unique determination of the unit.

We are storing the mac adress but really never using it but it can be used to identify the device if it is ever needed.

**Comment by brentm5** [comment]
I think that is a good apprach as long as the application on the itouch can handle saving the state persistently.  Also this api key would be unique for each device correct?  That way if we need to invalidate one device then we can do so. Also I am not sure what happens if we get into a scenario of the device has been setup somewhere and then we lose all data of devices some how or need to assign it somewhere else. I don't think we can rely on sending commands to the unit because of networking and whatnot.

**Comment by drapergeek** [comment]
Lets talk about one thing at a time. So yes, the API key would be correct and we would have to store the key on the device. We should definitely have a way to 're-register' a device if it loses its API key.

Now please explain the rest of your statement because I didn't understand it.

**Comment by brentm5** [comment]
I don't think sending commands to the devices would be reliable enough.  So I don't think we can push a command to reset the api key if something weird were to happen.  For example, if the api key were lost or someone accidentally  deleted the device record in the application.  Does that make sense?

**Comment by drapergeek** [comment]
I'm never going to push any data to the device. If someone deletes it we should ahve to go to the device and re-register it. In the case of removing an API key I think we should also have to go to the device. That is such a rare circumstance that I'm not too concerned about it.

**Comment by brentm5** [comment]
Alright then I think that is a good way to go about this.  Initial registration is through the mac address and we generate an api key give it back to the client to store and save the mac address and apikey in the database on the server side.  We could also just send the name of the device with the initial import and pre populate the name of the device for simplicity

**Comment by drapergeek** [comment]
Agreed, had already decided on that.

**Comment by brentm5** [comment]
Just making sure we were on the same page.
